install.packages("rvest")
install.packages("robotstxt")
install.packages("dplyr")
library(rvest)
library(robotstxt)
library(dplyr)
Path = paths_allowed("https://www.amazon.in/s?k=headphones")
link<-"https://www.amazon.in/s?k=headphones"
web<-read_html(link)
name=web%>%html_nodes(".a-color-base.a-text-normal")%>%html_text()
View(name)
dept=web%>%html_nodes(".a-price-whole")%>%html_text()
View(dept)
arrival<-web%>%html_nodes(".aok-align-bottom")%>%html_text()
View(arrival)
duration<-web%>%html_nodes(".a-text-bold")%>%html_text()
View(duration)
flights<-data.frame(name,dept,arrival,duration)
View(flights)
write.csv(flights,"flights data.csv")