install.packages("rvest")
install.packages("robotstxt")
install.packages("dplyr")
library(rvest)
library(robotstxt)
library(dplyr)
Path = paths_allowed("https://www.goibibo.com/hotels/hotels-in-munnar-ct/")
link<-("https://www.goibibo.com/hotels/hotels-in-munnar-ct/")
web<-read_html(link)
name=web%>%html_nodes(".dNdcuN")%>%html_text()
View(name)
rating=web%>%html_nodes(".iIlkKl")%>%html_text()
View(rating)
type<-web%>%html_nodes(".kyhlnC")%>%html_text()
View(type)
room<-web%>%html_nodes(".beCGEK")%>%html_text()
View(room)
hotels<-data.frame(name,rating,type,room)
View(hotels)
write.csv(hotels_munnar,"hotels_munnar data.csv")